### ISSUE TITLE
Menu Principal

### ISSUE THREAD

**Issue by ayelenMacarena** [ayelenMacarena/gdd#11]
No logueamos con administrador, hicimos click en el 3 boton del menu principal y dio error, nos gustaria saber que funcionalidad era pero su label no de veia por completo.

**Comment by ayelenMacarena** [comment]
La funcionalidad que fallaba era Ofertar/Comprar porque el admin no estaba logueado como persona. De todas formas dejo el Issue abierto parar que podamos mejorar el tema de los nombres en los labels.

**Comment by tatoviviani** [comment]
Me lo asigno, y agrego aca para no olvidarme de chequear y corregir todo el pasaje entre ventanas (que se abra todo Dentro del menu principal, y hacer redirecciones o "volver" donde corresponda)

**Comment by ayelenMacarena** [comment]
Dale, igual no se cuan necesario es el volver, porque al cerrar las ventanas de los distintos labels quedá ahi.

**Comment by ayelenMacarena** [comment]
@tatoviviani fijate que verifiqué lo del tercer label en modo administrador (antes había probado el tercer label en modo cliente y era comprar/ofertar) Creo (estoy casi segura) que el label que falla es cambiarContraseña . Si querés probalo con admin y vas a ver que está fallando . Avisame cualquier cosa si puedo darte una mano.

**Comment by tatoviviani** [comment]
cambiado el nombre de los botones y la navegacion de menues (el que rompia era administrar_rubro)
