### ISSUE TITLE
Menu principal - Faltan ABM

### ISSUE THREAD

**Issue by rodrigojb** [ayelenMacarena/gdd#14]
La ABM de facturas no se puede acceder desde ningún rol, en cual iría? Hay que agregarlo.

**Comment by tatoviviani** [comment]
Particularmente las funciones de "categorizar_publicacion", "facturas_realizadas" y "listado_estadistico", no se asignan a ningun rol en la Migracion (la parte de creacion de entidad Rol-Usuario), hay que modificar la migracion, y agregar esas 3 funciones al Rol que correspondan
(en mi opinion x lo que lei Facturas_realizadas es tanto de Cliente como de Empresa, pero Categorizar_publicacion y Listado_estadistico no estoy seguro)
Igual repito, si la implementacion ya esta creada, es solo agregar en la migracion la linea correspondiente.
