### ISSUE TITLE
Login + de 3 fallos

### ISSUE THREAD

**Issue by fecheromero** [ayelenMacarena/gdd#16]
Estuve probando y vi que suman los fallos pero nunca te sale un cartelito tipo diciendo: Supero los 3 intentos saraza saraza..

**Comment by ayelenMacarena** [comment]
Ya entendi lo que pasa, en los mismos intentos no sale. pero si la ponés mal y salis y volves a abrir si sale que tu usuario está inhabilidatado. 

Ahora lo arreglo

**Comment by ayelenMacarena** [comment]
Ya lo hablamos por ws. Queda asi .
