### ISSUE TITLE
Visibilidad

### ISSUE THREAD

**Issue by rodrigojb** [ayelenMacarena/gdd#19]
- Tira error de conversion de tipos al querer dar Alta a uno nuevo. Ver la cantidad de digitos que admiten los campos.
- En el listado puedo modificar el envio pero eso no se impacta, no deberia poder modificar ese check desde el listado.
- Cuando guardo una modificacion me debe llevar al listado de nuevo, no salir hasta atras de todo.
- Ver que el titulo dice Listado Rol.
- Sacar en el listado la fila por defecto vacia.

**Comment by tatoviviani** [comment]
Reparado el store que rompia por conversion de tipos
Bloqueada la modificacion de campos en el listado
Cambio la redireccion para volver al listado
Cambio el titulo a ListadoVisibilidad
Quitada la fila vacia por defecto
