### ISSUE TITLE
ComprarOfertar - Revisar Buscadores/Cant. Paginas/ Listado 

### ISSUE THREAD

**Issue by rodrigojb** [ayelenMacarena/gdd#2]
Se coloco como filtro, se muestren solo las publicaciones finalizadas a fin de poder probar el sistema, se debe corregir y poner se muestren las publicaciones activas.

**Comment by ayelenMacarena** [comment]
acordate de poner los comboBox no modificables.

**Comment by rodrigojb** [comment]
DO IT.
