### ISSUE TITLE
Ver tema fechas (punto 7 como no aprobar)

### ISSUE THREAD

**Issue by ayelenMacarena** [ayelenMacarena/gdd#4]

**Comment by tatoviviani** [comment]
Tengo entendido que este issue hace referencia a obtener la fecha seteada desde el app.config, de ser asi ya esta resuelto, y la validación para las otras fechas del sistema se deberían hacer contra dicha fecha, (queda en el issue de Validaciones)

**Comment by ayelenMacarena** [comment]
Lo habia dejado abierto porque  @rodrigojb no pudo usarlo, pero si lo pudieron usar cerremoslo.
